### ISSUE TITLE
Incomplete manifest?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-release/taskflow-release#1]
Not sure, but the manifest seems like it's missing some content:

https://github.com/ros-industrial-release/taskflow-release/blob/9fa1a76ec0f580a45d926b1598a1e1239d00b68e/noetic/package.xml#L2-L8

should this be fixed before the package is released?

Especially things like `license` and `author` and/or `maintainer` seem important to me.

**Comment by Levi-Armstrong** [comment]
I could not find anything that explicitly states who the author or maintainers were on the repository so I did not include to avoid incorrectly stating and the upstream is provided so those interested could go there for clarification. 

I believe this is the Author and Maintainer: Dr. Tsung-Wei Huang.

**Comment by gavanderhoorn** [comment]
> I could not find anything that explicitly states who the author or maintainers were on the repository so I did not include to avoid incorrectly stating and the upstream is provided so those interested could go there for clarification.

you can always just write something like "The Taskflow authors".

I've seen that done.
